Restricted MVT serving
gis-ops/tutorials pull request #56
Opened 2022-10-27 14:15 UTC by chrstnbwnkl

Adds a new tutorial on restricted access to geodata via Mapbox Vector Tiles. 

I'm not quite sure yet that this is ready: the last chunk of JS is quite long, but I feel like it needs to be in the tutorial, but on the other hand, there's little to explain, I think the most important parts are explained in the tutorial text. What do you think @nilsnolde ?

2022-10-27 17:11 UTC, nilsnolde requested changes
didn't go all the way, I stopped more or less before the JS part, because I wouldn't be able to run it in its current state. there's quite a few problems with the python code, mostly imports missing which is not so painful, but I have little idea what `Tile` is supposed to be..

generally it's cool functionality and the full experience just needs some JS code and a few more lines of python. I do think the code blocks could use a few more in-code comments what's happening, also in the JS code:)

2022-10-28 07:10 UTC, chrstnbwnkl commented on webservices/fastapi/fastapi_auth_vector_tiles.md
> +    tms = morecantile.tms.get("WebMercatorQuad")
Usually you're right, but in the context of this tutorial, I think it's actually better to leave the code where it makes sense to explain it.

2022-10-28 07:26 UTC, nilsnolde commented on webservices/fastapi/fastapi_auth_vector_tiles.md
> +    tms = morecantile.tms.get("WebMercatorQuad")
haha true!

2022-10-28 07:49 UTC, chrstnbwnkl commented on webservices/fastapi/fastapi_auth_vector_tiles.md
> +        return get_user_info(self.user)
this was on purpose as well, to make clear that the method just calls a function internally that actually holds the logic

2022-10-28 10:27 UTC, nilsnolde approved these changes
jep thanks, looks good! didn't test it again though, but no need if you just did that.

2022-10-28 10:27 UTC, merged